name: MetalSmith
favicon: null
layout_spectrum: 0.5329
typography_spectrum: 0.76307
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#53575a'
    - '#0a0700'
    - '#75b61a'
    - '#c5c4c2'
  brandStrength: 0.6514087934046984
  lightness: 0.7802919012028724
  saturation: 0.7843975271098316
  rhythmicContrast: 0.8260499394964427
purpose: []
